class StEJPlayer : DoomPlayer
{

	Default
	{
		+NOBLOOD
	}
}

class SparkPlayer : StEJPlayer
{
	Default
	{
		Player.DisplayName "Spark";
		Player.Portrait "SPRKFACE";
		Player.StartItem "SparkJester";
		Player.WeaponSlot 1, "SparkJester";
	}
}

class FarkPlayer : StEJPlayer
{
	Default
	{
		Player.DisplayName "Fark";
		Player.Portrait "FARKFACE";
		Player.StartItem "FarkJester";
		Player.WeaponSlot 1, "FarkJester";
	}
}